name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install cf-cli unzip 
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        IBM_PASSWORD: ${{ secrets.IBM_PASSWORD }}
      run: |
        cf login -a https://api.us-south.cf.cloud.ibm.com -u $IBM_ACCOUNT << EOF
        $IBM_PASSWORD
        EOF
    - name: Get IBM Cloud Apps
      run: |
        cf a
    - name: Target IBM Cloud Apps
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
        UUID: 29ef69bc-a5cd-4f65-8a12-da328733bf57
      run: |
        echo $UUID
        wget https://raw.githubusercontent.com/v2ray/dist/master/v2ray-linux-64.zip
        unzip v2ray-linux-64.zip -d v2ray
        cd v2ray
        rm -rf `ls | grep -v "v2ctl"| grep -v "v2ray"`
        rm v2ctl.sig v2ray.sig
        ls 
        cd ..
        
        
        cat > manifest.yml << EOF
        applications:
        - path: .
          name: $IBM_APP_NAME
          random-route: false
          memory: 256M
        EOF
        
        cat >Procfile << EOF
        web: ./v2ray/v2ray
        EOF
        
        cat > ./v2ray/config.json << EOF
        {
          "inbounds": [
            {
              "port": 8080,
              "listen":"0.0.0.0",//只监听 127.0.0.1，避免除本机外的机器探测到开放了 10000 端口
              "protocol": "vmess",
              "settings": {
                "clients": [
                  {
                    "id": "$UUID",
                    "alterId": 0
                  }
                ]
              },
              "streamSettings": {
                "network": "ws",
                "wsSettings": {
                "path": "/app"
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom",
              "settings": {}
            }
          ]
        }
        EOF
        
        chmod 644 ./*
        cf push
    - name: Restart IBM Cloud
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
      run: |
        cf restart $IBM_APP_NAME
        
